services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy-cloudflare
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - /hosted/docker/caddy-cloudflare/config/Caddyfile:/etc/caddy/Caddyfile
      - /hosted/docker/caddy-cloudflare/data:/data
      - /hosted/docker/caddy-cloudflare/config/caddy:/config
    extra_hosts:
      - host.docker.internal:host-gateway
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    networks:
      - caddy_network
networks:
  caddy_network:
    driver: bridge
