services:
  db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "${TZ}"
    volumes:
      - nextcloud_db:/var/lib/mysql
    networks: [nextnet]

  redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - nextcloud_redis:/data
    networks: [nextnet]

  app:
    image: nextcloud:30-apache
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on: [db, redis]
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
    volumes:
      - nextcloud_app:/var/www/html
    ports:
      - "127.0.0.1:8081:80"   # local for LAN Caddy
      - "${WG_IP}:8081:80" # bind to WireGuard IP only
    networks: [nextnet]

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: nextcloud-onlyoffice
    restart: unless-stopped
    environment:
      JWT_ENABLED: "true"
      JWT_SECRET: ${ONLYOFFICE_JWT_SECRET}
    ports:
      - "127.0.0.1:8082:80"   # local for LAN Caddy
      - "${WG_IP}:8082:80"
    networks: [nextnet]

networks:
  nextnet:

volumes:
  nextcloud_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /pool/hosted/docker/nextcloud/db
  nextcloud_redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /pool/hosted/docker/nextcloud/redis
  nextcloud_app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /pool/hosted/docker/nextcloud/app
