repos:
  # Python formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0 # use latest stable
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
  # Bash formatting
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci"]
  # Enforce LF line endings
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
  # Strip trailing whitespace, fix EOFs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        #  - repo: https://github.com/google/yamlfmt
        #    rev: v0.17.2
        #    hooks:
        #      - id: yamlfmt
