site_name: Bitrealm Homelab
site_description: Docs for my homelab, NAS, and VPS setup
site_url: https://mbeisser1.github.io/homelab/
repo_url: https://github.com/mbeisser1/homelab
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: slate

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.snippets
  - tables

plugins:
  - search

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

extra:
  mermaid:
    theme: dark

nav:
  - Home: index.md
  - Homelab:
      - Overview: homelab/overview.md
      - Network: homelab/network.md
      - WireGuard: homelab/wireguard.md
      - Caddy: homelab/caddy.md
      - Fail2ban: homelab/fail2ban.md
      - NAS:
          - Scripts: homelab/nas/scripts.md
  - Projects:
      - SMS Tools: projects/sms.md
  - Downloads:
      - NAS Scripts: homelab/nas/scripts.md
      - SMS Tools: projects/sms.md
