version: "3.9"
services:
  obsidian:
    image: ghcr.io/sytone/obsidian-remote:latest
    container_name: obsidian
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=20250
      - TZ=America/New_York
      - HOME=/config # ensure .Xauthority lives where we have write perms
      - XDG_RUNTIME_DIR=/config/runtime
      - CUSTOM_PORT=8080
      - CUSTOM_HTTPS_PORT=8443
      - ELECTRON_DISABLE_GPU=1
      # Optional HTTP basic auth:
      # - CUSTOM_USER=levix
      # - PASSWORD=supersecret
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=pandoc texlive-xetex
    ports:
      - "8280:8080"
      - "8443:8443"
    volumes:
      - /pool/hosted/docker/obsidian/config:/config
      - /pool/hosted/docker/obsidian/vault:/vaults
