services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:2025.10.0
    container_name: cloudflared-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_NAME=bitrealm-cloudflare-tunnel
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./config:/etc/cloudflared
    command: tunnel --no-autoupdate run
