networks:
  bridge:
    driver: bridge

services:
  # The container that runs XWiki in Tomcat, with the appropriate JDBC driver (for postgres).
  web:
    image: "xwiki:${XWIKI_VERSION}-postgres-tomcat"
    container_name: xwiki
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8380:8080" # Host port 8380 → Container port 8080
    # The DB_USER/DB_PASSWORD/DB_DATABASE/DB_HOST variables are used in the hibernate.cfg.xml file.
    environment:
      - XWIKI_VERSION=${XWIKI_VERSION}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=db

      # Reverse proxy support
      - TOMCAT_ENABLE_REMOTEIPVALVE=true

      # JVM tuning
      #- JAVA_OPTS=-Xms2g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:+ExplicitGCInvokesConcurrent -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -Dfile.encoding=UTF-8
    volumes:
      - /hosted/docker/xwiki/web:/usr/local/xwiki
      #- /hosted/docker/xwiki2/config/hibernate.cfg.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/hibernate.cfg.xml
    networks:
      - bridge

  # The container that runs the database (postgres)
  db:
    image: "postgres:17"
    container_name: xwiki-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale-provider=builtin --locale=C.UTF-8
      #- POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /hosted/docker/xwiki/db:/var/lib/postgresql/data
      #- /hosted/docker/xwiki2/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      #- /hosted/docker/xwiki/config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro      
    #command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    #command: ["postgres", "-c", "listen_addresses=*"]
    networks:
      - bridge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xwiki -d xwiki"]
      #test: ["CMD", "wget", "--spider", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 5
        #start_period: 120s  # Critical: Gives XWiki 2 minutes to initialize
