---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:2.1.1
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=20250 # hosted group
      - TZ=Etc/UTC
    volumes:
      - /opt/syncthing/config:/config
      - /pool/docs:/obsidian
    #network_mode: host
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

