services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:2025.10.0
    container_name: cloudflare-tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_NAME=bitrealm-cloudflare-tunnel
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    volumes:
      - ./config:/etc/cloudflared
    command: tunnel --no-autoupdate run
    networks:
      - internal-net
    depends_on:
      - nginx-pm

  nginx-pm:
    image: 'jc21/nginx-proxy-manager:2.12.6'
    container_name: nginx-pm
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
      - '8081:81'
    volumes:
      - /hosted/docker/nginx-proxy-manager/data:/data
      - /hosted/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge