services:
  dockge:
    image: louislam/dockge:1.5.0
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
        
      # Updated stacks directory path
      - /home/mbeisser/docker_compose:/home/mbeisser/docker_compose
    environment:
      # Updated to match your stacks directory
      - DOCKGE_STACKS_DIR=/home/mbeisser/docker_compose
