name: Build & Deploy Docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Stage downloadable files from your repo into docs/_downloads/
      - name: Stage downloadable files
        run: |
          set -eux
          rm -rf docs/_downloads
          mkdir -p docs/_downloads

          # Copy from nas/
          rsync -a \
            --include='*/' \
            --include='*.sh' --include='*.py' --include='*.js' \
            --include='*.conf' --include='*.cfg' --include='*.service' --include='*.timer' \
            --include='rc.local' \
            --exclude='*' \
            nas/ docs/_downloads/nas/

          # Copy from projects/
          rsync -a \
            --include='*/' \
            --include='*.sh' --include='*.py' --include='*.js' \
            --exclude='*' \
            projects/ docs/_downloads/projects/

          # Copy from archive/
          rsync -a \
            --include='*/' \
            --include='*.sh' --include='*.py' --include='*.js' \
            --include='*.conf' --include='*.cfg' --include='rc.local' \
            --exclude='*' \
            archive/ docs/_downloads/archive/

      - run: pip install mkdocs-material pymdown-extensions
      - run: mkdocs build --strict

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - id: deployment
        uses: actions/deploy-pages@v4
