name: Build & Deploy Docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install mkdocs-material pymdown-extensions
      - name: Stage downloadable files
        run: |
          set -eux
          # start fresh
          rm -rf docs/_downloads
          mkdir -p docs/_downloads
          # mirror only certain file types from these source dirs
          rsync -a \
            --include='*/' \
            --include='*.sh' --include='*.py' \
            --include='*.conf' --include='*.cfg' --include='*.service' --include='*.timer' \
            --exclude='*' \
            nas/ docs/_downloads/nas/ || true
          rsync -a \
            --include='*/' \
            --include='*.sh' --include='*.py' \
            --exclude='*' \
            projects/ docs/_downloads/projects/ || true
          rsync -a \
            --include='*/' \
            --include='*.sh' --include='*.py' --include='*.conf' --include='*.cfg' \
            --exclude='*' \
            archive/ docs/_downloads/archive/ || true
      - run: mkdocs build --strict
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - uses: actions/deploy-pages@v4

